let npc = {
  name: "",
  type: "npc",
  items: [],
  flags: {},
  data: {
    abilities: {
      cha: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
      con: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
      dex: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
      int: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
      str: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
      wis: { value: 10, min: 3, proficient: 0, mod: 0, save: 0 },
    },
    attributes: {
      ac: { min: 0, value: 0 },
      hp: { value: 10, min: 0, max: 10, temp: 0, tempmax: 0, formula: "" },
      init: { value: 0, bonus: 0, mod: 0, prof: 0, total: 0 },
      prof: 2,
      speed: { value: "30 ft", special: "" },
      spellcasting: "int",
      spelldc: 10,
    },
    currency: {
      cp: 0,
      ep: 0,
      gp: 0,
      pp: 0,
      sp: 0,
    },
    details: {
      alignment: "",
      biography: { value: "", public: "" },
      cr: 1,
      environment: "",
      race: "",
      source: "",
      type: "",
      xp: { value: 200 },
      spellLevel: 0,
    },
    resources: {
      lair: { value: false, initiative: 0 },
      legact: { value: 0, max: 0 },
      legres: { value: 0, max: 0 },
    },
    skills: {
      acr: { value: 0, ability: "dex", bonus: 0, mod: 0, passive: 10 },
      ani: { value: 0, ability: "wis", bonus: 0, mod: 0, passive: 10 },
      arc: { value: 0, ability: "int", bonus: 0, mod: 0, passive: 10 },
      ath: { value: 0, ability: "str", bonus: 0, mod: 0, passive: 10 },
      dec: { value: 0, ability: "cha", bonus: 0, mod: 0, passive: 10 },
      his: { value: 0, ability: "int", bonus: 0, mod: 0, passive: 10 },
      ins: { value: 0, ability: "wis", bonus: 0, mod: 0, passive: 10 },
      inv: { value: 0, ability: "int", bonus: 0, mod: 0, passive: 10 },
      itm: { value: 0, ability: "cha", bonus: 0, mod: 0, passive: 10 },
      med: { value: 0, ability: "wis", bonus: 0, mod: 0, passive: 10 },
      nat: { value: 0, ability: "int", bonus: 0, mod: 0, passive: 10 },
      per: { value: 0, ability: "cha", bonus: 0, mod: 0, passive: 10 },
      prc: { value: 0, ability: "wis", bonus: 0, mod: 0, passive: 10 },
      prf: { value: 0, ability: "cha", bonus: 0, mod: 0, passive: 10 },
      rel: { value: 0, ability: "int", bonus: 0, mod: 0, passive: 10 },
      slt: { value: 0, ability: "dex", bonus: 0, mod: 0, passive: 10 },
      ste: { value: 0, ability: "dex", bonus: 0, mod: 0, passive: 10 },
      sur: { value: 0, ability: "wis", bonus: 0, mod: 0, passive: 10 },
    },
    spells: {
      spell0: { value: 0, max: 0 },
      spell1: { value: 0, max: 0 },
      spell2: { value: 0, max: 0 },
      spell3: { value: 0, max: 0 },
      spell4: { value: 0, max: 0 },
      spell5: { value: 0, max: 0 },
      spell6: { value: 0, max: 0 },
      spell7: { value: 0, max: 0 },
      spell8: { value: 0, max: 0 },
      spell9: { value: 0, max: 0 },
    },
    traits: {
      ci: { value: Array(0), custom: "" },
      di: { value: Array(0), custom: "" },
      dr: { value: Array(0), custom: "" },
      dv: { value: Array(0), custom: "" },
      languages: { value: Array(0), custom: "" },
      senses: "",
      size: "med",
    },
  },
}
