// fallow-ignore-file
// This file is auto-generated by _linkBuilder.js. Do not edit directly.
export { default as PartiallyAmphibious } from "./PartiallyAmphibious";
export { default as VedalkenDispassion } from "./VedalkenDispassion";

