// fallow-ignore-file
// This file is auto-generated by _linkBuilder.js. Do not edit directly.
export { default as ClawsDexterity } from "./ClawsDexterity";
export { default as NaturalAttackClaws } from "./NaturalAttackClaws";

