/** Stable identities and fallback metadata from dnd5e 6.0.x; configured names/artwork take precedence. */
export const SYSTEM_ICON_PRESETS: readonly Omit<ISystemIcon, "color">[] = [
  {
    id: "acid",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Acid",
    path: "systems/dnd5e/icons/svg/damage/acid.svg",
    fallbackName: "Acid",
  },
  {
    id: "bludgeoning",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Bludgeoning",
    path: "systems/dnd5e/icons/svg/damage/bludgeoning.svg",
    fallbackName: "Bludgeoning",
  },
  {
    id: "cold",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Cold",
    path: "systems/dnd5e/icons/svg/damage/cold.svg",
    fallbackName: "Cold",
  },
  {
    id: "fire",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Fire",
    path: "systems/dnd5e/icons/svg/damage/fire.svg",
    fallbackName: "Fire",
  },
  {
    id: "force",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Force",
    path: "systems/dnd5e/icons/svg/damage/force.svg",
    fallbackName: "Force",
  },
  {
    id: "lightning",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Lightning",
    path: "systems/dnd5e/icons/svg/damage/lightning.svg",
    fallbackName: "Lightning",
  },
  {
    id: "necrotic",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Necrotic",
    path: "systems/dnd5e/icons/svg/damage/necrotic.svg",
    fallbackName: "Necrotic",
  },
  {
    id: "piercing",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Piercing",
    path: "systems/dnd5e/icons/svg/damage/piercing.svg",
    fallbackName: "Piercing",
  },
  {
    id: "poison",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Poison",
    path: "systems/dnd5e/icons/svg/damage/poison.svg",
    fallbackName: "Poison",
  },
  {
    id: "psychic",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Psychic",
    path: "systems/dnd5e/icons/svg/damage/psychic.svg",
    fallbackName: "Psychic",
  },
  {
    id: "radiant",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Radiant",
    path: "systems/dnd5e/icons/svg/damage/radiant.svg",
    fallbackName: "Radiant",
  },
  {
    id: "slashing",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Slashing",
    path: "systems/dnd5e/icons/svg/damage/slashing.svg",
    fallbackName: "Slashing",
  },
  {
    id: "thunder",
    category: "damage",
    name: "DND5E.DAMAGE.Type.Thunder",
    path: "systems/dnd5e/icons/svg/damage/thunder.svg",
    fallbackName: "Thunder",
  },
  {
    id: "bleeding",
    category: "status",
    name: "EFFECT.DND5E.StatusBleeding",
    path: "systems/dnd5e/icons/svg/statuses/bleeding.svg",
    fallbackName: "Bleeding",
  },
  {
    id: "blinded",
    category: "status",
    name: "DND5E.ConBlinded",
    path: "systems/dnd5e/icons/svg/statuses/blinded.svg",
    fallbackName: "Blinded",
  },
  {
    id: "bloodied",
    category: "status",
    name: "EFFECT.DND5E.StatusBloodied",
    path: "systems/dnd5e/icons/svg/statuses/bloodied.svg",
    fallbackName: "Bloodied",
  },
  {
    id: "burning",
    category: "status",
    name: "EFFECT.DND5E.StatusBurning",
    path: "systems/dnd5e/icons/svg/statuses/burning.svg",
    fallbackName: "Burning",
  },
  {
    id: "burrowing",
    category: "status",
    name: "EFFECT.DND5E.StatusBurrowing",
    path: "systems/dnd5e/icons/svg/statuses/burrowing.svg",
    fallbackName: "Burrowing",
  },
  {
    id: "charmed",
    category: "status",
    name: "DND5E.ConCharmed",
    path: "systems/dnd5e/icons/svg/statuses/charmed.svg",
    fallbackName: "Charmed",
  },
  {
    id: "concentrating",
    category: "status",
    name: "EFFECT.DND5E.StatusConcentrating",
    path: "systems/dnd5e/icons/svg/statuses/concentrating.svg",
    fallbackName: "Concentrating",
  },
  {
    id: "coverHalf",
    category: "status",
    name: "EFFECT.DND5E.StatusHalfCover",
    path: "systems/dnd5e/icons/svg/statuses/cover-half.svg",
    fallbackName: "Half Cover",
  },
  {
    id: "coverThreeQuarters",
    category: "status",
    name: "EFFECT.DND5E.StatusThreeQuartersCover",
    path: "systems/dnd5e/icons/svg/statuses/cover-three-quarters.svg",
    fallbackName: "Three-Quarters Cover",
  },
  {
    id: "coverTotal",
    category: "status",
    name: "EFFECT.DND5E.StatusTotalCover",
    path: "systems/dnd5e/icons/svg/statuses/cover-total.svg",
    fallbackName: "Total Cover",
  },
  {
    id: "cursed",
    category: "status",
    name: "EFFECT.DND5E.StatusCursed",
    path: "systems/dnd5e/icons/svg/statuses/cursed.svg",
    fallbackName: "Cursed",
  },
  {
    id: "dead",
    category: "status",
    name: "EFFECT.DND5E.StatusDead",
    path: "systems/dnd5e/icons/svg/statuses/dead.svg",
    fallbackName: "Dead",
  },
  {
    id: "deafened",
    category: "status",
    name: "DND5E.ConDeafened",
    path: "systems/dnd5e/icons/svg/statuses/deafened.svg",
    fallbackName: "Deafened",
  },
  {
    id: "dehydration",
    category: "status",
    name: "EFFECT.DND5E.StatusDehydration",
    path: "systems/dnd5e/icons/svg/statuses/dehydration.svg",
    fallbackName: "Dehydration",
  },
  {
    id: "diseased",
    category: "status",
    name: "DND5E.ConDiseased",
    path: "systems/dnd5e/icons/svg/statuses/diseased.svg",
    fallbackName: "Diseased",
  },
  {
    id: "dodging",
    category: "status",
    name: "EFFECT.DND5E.StatusDodging",
    path: "systems/dnd5e/icons/svg/statuses/dodging.svg",
    fallbackName: "Dodging",
  },
  {
    id: "encumbered",
    category: "status",
    name: "EFFECT.DND5E.StatusEncumbered",
    path: "systems/dnd5e/icons/svg/statuses/encumbered.svg",
    fallbackName: "Encumbered",
  },
  {
    id: "ethereal",
    category: "status",
    name: "EFFECT.DND5E.StatusEthereal",
    path: "systems/dnd5e/icons/svg/statuses/ethereal.svg",
    fallbackName: "Ethereal",
  },
  {
    id: "exceedingCarryingCapacity",
    category: "status",
    name: "EFFECT.DND5E.StatusExceedingCarryingCapacity",
    path: "systems/dnd5e/icons/svg/statuses/exceeding-carrying-capacity.svg",
    fallbackName: "Exceeding Carrying Capacity",
  },
  {
    id: "exhaustion",
    category: "status",
    name: "DND5E.ConExhaustion",
    path: "systems/dnd5e/icons/svg/statuses/exhaustion.svg",
    fallbackName: "Exhaustion",
  },
  {
    id: "falling",
    category: "status",
    name: "EFFECT.DND5E.StatusFalling",
    path: "systems/dnd5e/icons/svg/statuses/falling.svg",
    fallbackName: "Falling",
  },
  {
    id: "flying",
    category: "status",
    name: "EFFECT.DND5E.StatusFlying",
    path: "systems/dnd5e/icons/svg/statuses/flying.svg",
    fallbackName: "Flying",
  },
  {
    id: "frightened",
    category: "status",
    name: "DND5E.ConFrightened",
    path: "systems/dnd5e/icons/svg/statuses/frightened.svg",
    fallbackName: "Frightened",
  },
  {
    id: "grappled",
    category: "status",
    name: "DND5E.ConGrappled",
    path: "systems/dnd5e/icons/svg/statuses/grappled.svg",
    fallbackName: "Grappled",
  },
  {
    id: "heavilyEncumbered",
    category: "status",
    name: "EFFECT.DND5E.StatusHeavilyEncumbered",
    path: "systems/dnd5e/icons/svg/statuses/heavily-encumbered.svg",
    fallbackName: "Heavily Encumbered",
  },
  {
    id: "hiding",
    category: "status",
    name: "EFFECT.DND5E.StatusHiding",
    path: "systems/dnd5e/icons/svg/statuses/hiding.svg",
    fallbackName: "Hiding",
  },
  {
    id: "hovering",
    category: "status",
    name: "EFFECT.DND5E.StatusHovering",
    path: "systems/dnd5e/icons/svg/statuses/hovering.svg",
    fallbackName: "Hovering",
  },
  {
    id: "incapacitated",
    category: "status",
    name: "DND5E.ConIncapacitated",
    path: "systems/dnd5e/icons/svg/statuses/incapacitated.svg",
    fallbackName: "Incapacitated",
  },
  {
    id: "invisible",
    category: "status",
    name: "DND5E.ConInvisible",
    path: "systems/dnd5e/icons/svg/statuses/invisible.svg",
    fallbackName: "Invisible",
  },
  {
    id: "malnutrition",
    category: "status",
    name: "EFFECT.DND5E.StatusMalnutrition",
    path: "systems/dnd5e/icons/svg/statuses/malnutrition.svg",
    fallbackName: "Malnutrition",
  },
  {
    id: "marked",
    category: "status",
    name: "EFFECT.DND5E.StatusMarked",
    path: "systems/dnd5e/icons/svg/statuses/marked.svg",
    fallbackName: "Marked",
  },
  {
    id: "paralyzed",
    category: "status",
    name: "DND5E.ConParalyzed",
    path: "systems/dnd5e/icons/svg/statuses/paralyzed.svg",
    fallbackName: "Paralyzed",
  },
  {
    id: "petrified",
    category: "status",
    name: "DND5E.ConPetrified",
    path: "systems/dnd5e/icons/svg/statuses/petrified.svg",
    fallbackName: "Petrified",
  },
  {
    id: "poisoned",
    category: "status",
    name: "DND5E.ConPoisoned",
    path: "systems/dnd5e/icons/svg/statuses/poisoned.svg",
    fallbackName: "Poisoned",
  },
  {
    id: "prone",
    category: "status",
    name: "DND5E.ConProne",
    path: "systems/dnd5e/icons/svg/statuses/prone.svg",
    fallbackName: "Prone",
  },
  {
    id: "restrained",
    category: "status",
    name: "DND5E.ConRestrained",
    path: "systems/dnd5e/icons/svg/statuses/restrained.svg",
    fallbackName: "Restrained",
  },
  {
    id: "silenced",
    category: "status",
    name: "EFFECT.DND5E.StatusSilenced",
    path: "systems/dnd5e/icons/svg/statuses/silenced.svg",
    fallbackName: "Silenced",
  },
  {
    id: "sleeping",
    category: "status",
    name: "EFFECT.DND5E.StatusSleeping",
    path: "systems/dnd5e/icons/svg/statuses/sleeping.svg",
    fallbackName: "Sleeping",
  },
  {
    id: "stable",
    category: "status",
    name: "EFFECT.DND5E.StatusStable",
    path: "systems/dnd5e/icons/svg/statuses/stable.svg",
    fallbackName: "Stable",
  },
  {
    id: "stunned",
    category: "status",
    name: "DND5E.ConStunned",
    path: "systems/dnd5e/icons/svg/statuses/stunned.svg",
    fallbackName: "Stunned",
  },
  {
    id: "suffocation",
    category: "status",
    name: "EFFECT.DND5E.StatusSuffocation",
    path: "systems/dnd5e/icons/svg/statuses/suffocation.svg",
    fallbackName: "Suffocation",
  },
  {
    id: "surprised",
    category: "status",
    name: "EFFECT.DND5E.StatusSurprised",
    path: "systems/dnd5e/icons/svg/statuses/surprised.svg",
    fallbackName: "Surprised",
  },
  {
    id: "transformed",
    category: "status",
    name: "EFFECT.DND5E.StatusTransformed",
    path: "systems/dnd5e/icons/svg/statuses/transformed.svg",
    fallbackName: "Transformed",
  },
  {
    id: "unconscious",
    category: "status",
    name: "DND5E.ConUnconscious",
    path: "systems/dnd5e/icons/svg/statuses/unconscious.svg",
    fallbackName: "Unconscious",
  },
];
