// fallow-ignore-file
// This file is auto-generated by _linkBuilder.js. Do not edit directly.
export { default as BreathWeapon } from "./BreathWeapon";
export { default as FrightfulAppearance } from "./FrightfulAppearance";

