import DDBEnricherFactoryMixin from "./mixins/DDBEnricherFactoryMixin";
import { GenericEnrichers, ItemEnrichers } from "./_module";
import { utils } from "../../lib/_module";
import { SRD_ITEM_SUMMONS } from "../companions/types/SRDItemSummonTable";

export default class DDBItemEnricher extends DDBEnricherFactoryMixin {
  constructor({ activityGenerator, notifier = null }: { activityGenerator: any; notifier?: any } = {} as any) {
    super({
      activityGenerator,
      effectType: "item",
      enricherType: "item",
      notifier,
      ddbActionType: "item",
    });
  }

  _defaultNameLoader(): any {
    const itemName = utils.pascalCase(this.name);
    if (!ItemEnrichers[itemName]) {
      return null;
    }
    return new ItemEnrichers[itemName]({
      ddbEnricher: this,
    });
  }

  NAME_HINTS: Record<string, string> = {
    "Alchemist's Fire (flask)": "Alchemist's Fire",
    "Potion of Greater Healing": "Potion of Healing (Greater)",
    "Potion of Superior Healing": "Potion of Healing (Superior)",
    "Potion of Supreme Healing": "Potion of Healing (Supreme)",
    // an exact name: the TGC printing only; "Revolver of Warning" and "Revolver, +1" are other items
    "Revolver (TGC)": "Revolver",
    // 2014 printings name the delivery method; the 2024 reprints do not
    "Assassin's Blood (Ingested)": "Assassin's Blood",
    "Assassin’s Blood (Ingested)": "Assassin's Blood",
    "Burnt Othur Fumes (Inhaled)": "Burnt Othur Fumes",
    "Delerium Chip": "Delerium",
    "Delerium Crystal": "Delerium",
    "Delerium Fragment": "Delerium",
    "Delerium Geode": "Delerium",
    "Delerium Massive Cluster": "Delerium",
    "Delerium Shard": "Delerium",
    "Kobbold Flaymefrower (Very Rare)": "Kobbold Flaymefrower Coldfire",
  };

  NAME_HINT_INCLUDES: Record<string, string> = {
    // every summoning item in the table routes to the one table-driven enricher
    ...Object.fromEntries(SRD_ITEM_SUMMONS.map((entry) => [entry.match, "SRD Summon Item"])),
    "Absorbing Tattoo": "Absorbing Tattoo",
    "Banjo of Ol' Jericho Sticks": "Banjo of Ol' Jericho Sticks",
    "Banjo of Ol’ Jericho Sticks": "Banjo of Ol' Jericho Sticks",
    "Bell of the Dusk Mother": "Bell of the Dusk Mother",
    "Cabal's Ruin": "Cabal's Ruin",
    "Clematis-tainted": "Clematis-tainted Weapon",
    "Flame Tongue": "Flame Tongue",
    "Ghaal'Shaarat": "Ghaal'Shaarat",
    "Moon Sickle": "Moon Sickle",
    // the gem variants name their Beast form in parentheses
    "Necklace of the Beastly Familiar": "Necklace of the Beastly Familiar",
    "Dragon Wing": "Dragon Wing",
    "Hammer of Thunderbolts": "Hammer of Thunderbolts",
    "Holy Avenger": "Holy Avenger",
    "Wraps of Unarmed Power": "Wraps of Unarmed Power",
    "Wraps of Unarmed Prowess": "Wraps of Unarmed Power",
    "of the Vampire Lily Dragon": "Vampire Lily Dragon Armor",
    // Arcana Unleashed item families
    "Staff of Skulls": "Staff of Skulls",
    "Tramontane ": "Tramontane Armor",
    "Goading ": "Goading Ammunition",
    "Frost Brand": "Frost Brand",
    "Haemscale": "Haemscale",
    "Keyholes Dagger": "Keyholes Dagger",
    " of Grass": "Weapon of Grass",
    "Rhythm-Maker's Drum": "Rhythm-Maker's Drum",
    "Ring of Dedicated Focus": "Ring of Dedicated Focus",
    "Rod of the Pact Keeper": "Rod of the Pact Keeper",
    "Shovel of Yorgrim": "Shovel of Yorgrim",
    "Visage of the Old Ways": "Visage of the Old Ways",
    "Wave-Swept": "Wave-Swept Weapon",
    // the DM play-along reprint carries a "(DMLS)" suffix
    "Tarnished Idol of Good Fortunes": "Tarnished Idol of Good Fortunes",
    // the Breath Weapon printing lists its rarities as "(Rare)" variants
    "Potion of Dragon's Breath": "Potion of Dragon's Breath",
    "Potion of Dragon’s Breath": "Potion of Dragon's Breath",
    "Workshop Wrecker": "Workshop Wrecker",
    "Axe of the Galloping Headsman": "Axe of the Galloping Headsman",
    "Blunderbuss of the Grinning Sinner": "Blunderbuss of the Grinning Sinner",
    "Pneuma Greatsword": "Pneuma Blade",
    "Pneuma Longsword": "Pneuma Blade",
    "Tordalfr's Rebuttal": "Tordalfr's Rebuttal",
    "Tordalfr’s Rebuttal": "Tordalfr's Rebuttal",
    "Unstable Crumbler": "Unstable Crumbler",
    " of Wounding": "Weapon of Wounding",
    "Lash of Shadows": "Lash of Shadows",
    "Will of the Talon": "Will of the Talon",
    "Dragon's Wrath Weapon": "Dragon's Wrath Weapon",
    "Headbanger Lute": "Headbanger Lute",
    "Gunnspier": "Gunnspier",
    "Claws of Corruption": "Claws of Corruption",
    "Flooze": "Flooze",
    "Sword of the Crimson Abbot": "Sword of the Crimson Abbot",
    "The Bloody End": "The Bloody End",
    "Moonblade": "Moonblade",
    "Starcrossed ": "Starcrossed Weapon",
    "Ionbreaker": "Ionbreaker",
  };

  ENRICHERS: Record<string, EnricherConstructor> = {
    "Absorbing Tattoo": ItemEnrichers.AbsorbingTattoo,
    "Staff of Skulls": ItemEnrichers.StaffOfSkulls,
    "Tramontane Armor": ItemEnrichers.TramontaneArmor,
    "Goading Ammunition": ItemEnrichers.GoadingAmmunition,
    "Vampire Lily Dragon Armor": ItemEnrichers.VampireLilyDragonArmor,
    "Cabal's Ruin": ItemEnrichers.CabalsRuin,
    "Clematis-tainted Weapon": ItemEnrichers.ClematisTaintedWeapon,
    "Banjo of Ol' Jericho Sticks": ItemEnrichers.BanjoOfOlJerichoSticks,
    "Bell of the Dusk Mother": ItemEnrichers.BellOfTheDuskMother,
    "Phoenix Rocket Sword": ItemEnrichers.PhoenixRocketSword,
    "Requiem Bliss": ItemEnrichers.Requiem,
    "Requiem Clay": ItemEnrichers.Requiem,
    "Acid (vial)": ItemEnrichers.AcidVial,
    "Anstruth Harp": ItemEnrichers.InstrumentOfTheBards,
    "Alchemist's Fire": ItemEnrichers.AlchemistsFire,
    "Succulent Water of Life": ItemEnrichers.SucculentWaterOfLife,
    "Belashyrra's Beholder Crown": ItemEnrichers.BelashyrrasBeholderCrown,
    "Clematis Poison": ItemEnrichers.ClematisPoison,
    "Everlasting Sugarbomb": ItemEnrichers.EverlastingSugarbomb,
    "Muscle Graft": ItemEnrichers.MuscleGraft,
    "Sphere of Annihilation": ItemEnrichers.SphereOfAnnihilation,
    "Canaith Mandolin": ItemEnrichers.InstrumentOfTheBards,
    "Cli Lyre": ItemEnrichers.InstrumentOfTheBards,
    "Donjon's Sundering Sphere": ItemEnrichers.DonjonsSunderingSphere,
    "Doss Lute": ItemEnrichers.InstrumentOfTheBards,
    "Dragon Wing": ItemEnrichers.DragonWing,
    "Flame Tongue": ItemEnrichers.FlameTongue,
    "Fochlucan Bandore": ItemEnrichers.InstrumentOfTheBards,
    "Ghaal'Shaarat": ItemEnrichers.GhaalShaaratWeapon,
    "Hammer of Thunderbolts": ItemEnrichers.HammerOfThunderbolts,
    "Healer's Kit": ItemEnrichers.HealersKit,
    "Lantern, Bullseye": ItemEnrichers.BullseyeLantern,
    "Lantern, Hooded": ItemEnrichers.HoodedLantern,
    "Mac-Fuirmidh Cittern": ItemEnrichers.InstrumentOfTheBards,
    "Moon Sickle": ItemEnrichers.MoonSickle,
    "Ollamh Harp": ItemEnrichers.InstrumentOfTheBards,
    "Potion of Healing (Greater)": ItemEnrichers.PotionOfHealingGreater,
    "Potion of Healing (Superior)": ItemEnrichers.PotionOfHealingSuperior,
    "Potion of Healing (Supreme)": ItemEnrichers.PotionOfHealingSupreme,
    "Silent Hand Crossbow": ItemEnrichers.MistypedCrossbow,
    "Silent Heavy Crossbow": ItemEnrichers.MistypedCrossbow,
    "Silent Light Crossbow": ItemEnrichers.MistypedCrossbow,
    "Spell-Refueling Ring (Reaction)": ItemEnrichers.SpellRefuelingRingReaction,
    "Warrior's Passkey": ItemEnrichers.WarriorsPasskey,
    "Wraps of Unarmed Power": ItemEnrichers.WrapsOfUnarmedPower,
    "Shepherd’s Bane": ItemEnrichers.ShepherdsBane,
    "Shepherd's Bane": ItemEnrichers.ShepherdsBane,
    "Salamander Sauce": ItemEnrichers.UnarmedElementalPotion,
    "Last Rites Rum": ItemEnrichers.UnarmedElementalPotion,
    "Unarmed Strike": GenericEnrichers.UnarmedStrike,
    "Demon Breastplate": ItemEnrichers.DemonArmor,
    "Demon Chain Mail": ItemEnrichers.DemonArmor,
    "Demon Ring Mail": ItemEnrichers.DemonArmor,
    "Demon Chain Shirt": ItemEnrichers.DemonArmor,
    "Demon Half Plate Armor": ItemEnrichers.DemonArmor,
    "Demon Hide Armor": ItemEnrichers.DemonArmor,
    "Demon Leather Armor": ItemEnrichers.DemonArmor,
    "Demon Padded Armor": ItemEnrichers.DemonArmor,
    "Demon Plate Armor": ItemEnrichers.DemonArmor,
    "Demon Splint Armor": ItemEnrichers.DemonArmor,
    "Demon Scale Mail": ItemEnrichers.DemonArmor,
    "Hypnovulfen Figure": ItemEnrichers.HypnovulfenFigure,
    "Revolver": ItemEnrichers.Revolver,
    "Assassin's Blood": ItemEnrichers.AssassinsBlood,
    "Burnt Othur Fumes": ItemEnrichers.BurntOthurFumes,
    "Potion of Dragon's Breath": ItemEnrichers.PotionOfDragonsBreath,
    "Tarnished Idol of Good Fortunes": ItemEnrichers.TarnishedIdolOfGoodFortunes,
    "Workshop Wrecker": ItemEnrichers.WorkshopWrecker,
    "Weapon of Grass": ItemEnrichers.WeaponOfGrass,
    "Wave-Swept Weapon": ItemEnrichers.WaveSweptWeapon,
    "Visage of the Old Ways": ItemEnrichers.VisageOfTheOldWays,
    "Viol": ItemEnrichers.MusicalInstrumentChecks,
    "Three-Dragon Ante Set": ItemEnrichers.GamingSetChecks,
    "Three-Dragon Ante": ItemEnrichers.GamingSetChecks,
    "Three-dragon ante": ItemEnrichers.GamingSetChecks,
    "Shovel of Yorgrim": ItemEnrichers.ShovelOfYorgrim,
    "Shawm": ItemEnrichers.MusicalInstrumentChecks,
    "Rod of the Pact Keeper": ItemEnrichers.RodOfThePactKeeper,
    "Ring of X-ray Vision": ItemEnrichers.RingOfXRayVision,
    "Ring of Dedicated Focus": ItemEnrichers.RingOfDedicatedFocus,
    "Necklace of the Beastly Familiar": ItemEnrichers.NecklaceOfTheBeastlyFamiliar,
    "Rifle, Hunting": ItemEnrichers.HuntingRifle,
    "Rifle, Automatic": ItemEnrichers.AutomaticRifle,
    "Rhythm-Maker's Drum": ItemEnrichers.RhythmMakersDrum,
    "Playing Cards": ItemEnrichers.GamingSetChecks,
    "Playing Card Set": ItemEnrichers.GamingSetChecks,
    "Pistol, Automatic": ItemEnrichers.SemiautomaticPistol,
    "Pan Flute": ItemEnrichers.MusicalInstrumentChecks,
    "Lyre": ItemEnrichers.MusicalInstrumentChecks,
    "Lute": ItemEnrichers.MusicalInstrumentChecks,
    "Keyholes Dagger": ItemEnrichers.KeyholesDagger,
    "Horn": ItemEnrichers.MusicalInstrumentChecks,
    "Haemscale": ItemEnrichers.Haemscale,
    "Frost Brand": ItemEnrichers.FrostBrand,
    "Flute": ItemEnrichers.MusicalInstrumentChecks,
    "SRD Summon Item": ItemEnrichers.SRDSummonItem,
    "Dulcimer": ItemEnrichers.MusicalInstrumentChecks,
    "Drum": ItemEnrichers.MusicalInstrumentChecks,
    "Dragonchess Set": ItemEnrichers.GamingSetChecks,
    "Dragonchess": ItemEnrichers.GamingSetChecks,
    "Dice Set": ItemEnrichers.GamingSetChecks,
    "Dice": ItemEnrichers.GamingSetChecks,
    "Delerium": ItemEnrichers.Delerium,
    "Bagpipes": ItemEnrichers.MusicalInstrumentChecks,
    "Holy Avenger": ItemEnrichers.HolyAvenger,
    "Reaper's Scream": ItemEnrichers.ReapersScream,
    "Sunforger": ItemEnrichers.Sunforger,
    "Chitinous Club of c'Naazo": ItemEnrichers.ChitinousClubOfCNaazo,
    "Warhammer of Eruptions": ItemEnrichers.WarhammerOfEruptions,
    "Fife of Dragonsong": ItemEnrichers.FifeOfDragonsong,
    "Spellsword": ItemEnrichers.Spellsword,
    "Chillspike": ItemEnrichers.Chillspike,
    "Club of the Rook": ItemEnrichers.ClubOfTheRook,
    "Astral Sea Piercer": ItemEnrichers.AstralSeaPiercer,
    "Heaven's Gavel": ItemEnrichers.HeavensGavel,
    "Nightmare Staff": ItemEnrichers.NightmareStaff,
    "Eldritch Bident": ItemEnrichers.EldritchBident,
    "Ratbite": ItemEnrichers.Ratbite,
    "Failed Purity Spear": ItemEnrichers.FailedPuritySpear,
    "Mindrazor": ItemEnrichers.Mindrazor,
    "Sword of Kas": ItemEnrichers.SwordOfKas,
    "Prototype Thunderberd": ItemEnrichers.PrototypeThunderberd,
    "Prismatic Javelin": ItemEnrichers.PrismaticJavelin,
    "Flail of Tiamat": ItemEnrichers.FlailOfTiamat,
    "Gusting Blowgun": ItemEnrichers.GustingBlowgun,
    "Shooting Star": ItemEnrichers.ShootingStar,
    "Warhammer of Giant Felling": ItemEnrichers.WarhammerOfGiantFelling,
    "Slaying Longbow": ItemEnrichers.SlayingLongbow,
    "Trapper's Teeth": ItemEnrichers.TrappersTeeth,
    "Hazirawn": ItemEnrichers.Hazirawn,
    "Royal Incinerator": ItemEnrichers.RoyalIncinerator,
    "Staff of the Magi": ItemEnrichers.StaffOfTheMagi,
    "Staff of Power": ItemEnrichers.StaffOfPower,
    "Ionbreaker": ItemEnrichers.Ionbreaker,
    "Starcrossed Weapon": ItemEnrichers.StarcrossedWeapon,
    "Moonblade": ItemEnrichers.Moonblade,
    "The Bloody End": ItemEnrichers.TheBloodyEnd,
    "Sword of the Crimson Abbot": ItemEnrichers.SwordOfTheCrimsonAbbot,
    "Flooze": ItemEnrichers.Flooze,
    "Claws of Corruption": ItemEnrichers.ClawsOfCorruption,
    "Gunnspier": ItemEnrichers.Gunnspier,
    "Headbanger Lute": ItemEnrichers.HeadbangerLute,
    "Dragon's Wrath Weapon": ItemEnrichers.DragonsWrathWeapon,
    "Will of the Talon": ItemEnrichers.WillOfTheTalon,
    "Lash of Shadows": ItemEnrichers.LashOfShadows,
    "Weapon of Wounding": ItemEnrichers.WeaponOfWounding,
    "Unstable Crumbler": ItemEnrichers.UnstableCrumbler,
    "Tordalfr's Rebuttal": ItemEnrichers.TordalfrsRebuttal,
    "Pneuma Blade": ItemEnrichers.PneumaBlade,
    "Kobbold Flaymefrower Coldfire": ItemEnrichers.KobboldFlaymefrowerColdfire,
    "Blunderbuss of the Grinning Sinner": ItemEnrichers.BlunderbussOfTheGrinningSinner,
    "Axe of the Galloping Headsman": ItemEnrichers.AxeOfTheGallopingHeadsman,
  };

  FALLBACK_ENRICHERS: Record<string, EnricherConstructor> = {};
}
