import { DirectoryPicker } from "./lib/DirectoryPicker.js";

const SETTINGS = {
  MODULE_ID: "ddb-importer",
  FLAG_NAME: "ddbimporter",
  MODULE_NAME: "D&D Beyond Importer",
  DEFAULT_SETTINGS: {
    // these settigs are loaded during renderSidebarTab
    EARLY: {
      "log-level": {
        name: "ddb-importer.settings.log-level.name",
        hint: "ddb-importer.settings.log-level.hint",
        scope: "world",
        config: true,
        type: String,
        choices: {
          DEBUG: "DEBUG",
          INFO: "INFO",
          WARN: "WARN",
          ERR: "ERROR ",
          OFF: "OFF",
        },
        default: "INFO",
      },
      "show-munch-top": {
        name: "ddb-importer.settings.show-munch-top.name",
        hint: "ddb-importer.settings.show-munch-top.hint",
        scope: "world",
        config: true,
        type: Boolean,
        default: true,
      },
      "patreon-tier": {
        scope: "world",
        config: false,
        type: String,
        default: null,
      },
      "custom-proxy": {
        name: "ddb-importer.settings.custom-proxy.name",
        hint: "ddb-importer.settings.custom-proxy.hint",
        scope: "world",
        config: false,
        type: Boolean,
        default: false,
      },
      "encounter-muncher-enabled": {
        scope: "world",
        config: false,
        type: Boolean,
        default: true,
      },
    },
    // ready settings
    READY: {
      // settings for settings management
      SETTINGS: {
        "auto-create-compendium": {
          scope: "world",
          config: false,
          type: Boolean,
          default: true,
        },
      },
      COMPENDIUMS: {
        "entity-item-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-feature-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-class-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-race-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-trait-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-feat-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-spell-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-override-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-table-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
        "entity-monster-compendium": {
          scope: "world",
          config: false,
          type: String,
        },
      },
      // dir locations
      DIRECTORIES: {
        "image-upload-directory": {
          name: "ddb-importer.settings.image-upload-directory.name",
          hint: "ddb-importer.settings.image-upload-directory.hint",
          scope: "world",
          config: false,
          type: DirectoryPicker.Directory,
          default: "[data] ddb-images/characters",
        },
        "other-image-upload-directory": {
          name: "ddb-importer.settings.image-upload-directory.name",
          hint: "ddb-importer.settings.image-upload-directory.hint",
          scope: "world",
          config: false,
          type: DirectoryPicker.Directory,
          default: "[data] ddb-images/other",
        },
        "frame-image-upload-directory": {
          scope: "world",
          config: false,
          type: DirectoryPicker.Directory,
          default: "[data] ddb-images/frames",
        },
        "adventure-import-path": {
          name: "ddb-importer.settings.adventure-import-path.name",
          hint: "ddb-importer.settings.adventure-import-path.hint",
          scope: "world",
          config: true,
          default: "[data] adventures/import",
          type: DirectoryPicker.Directory,
        },
        "adventure-upload-path": {
          name: "ddb-importer.settings.adventure-upload-path.name",
          hint: "ddb-importer.settings.adventure-upload-path.hint",
          scope: "world",
          config: true,
          default: "[data] ddb-images/adventures",
          type: DirectoryPicker.Directory,
        },
        "adventure-misc-path": {
          name: "ddb-importer.settings.adventure-misc-path.name",
          hint: "ddb-importer.settings.adventure-misc-path.hint",
          scope: "world",
          config: true,
          default: "[data] ddb-images/adventures/misc",
          type: DirectoryPicker.Directory,
        },
      },
      UI: {
        "monster-link-title": {
          name: "ddb-importer.settings.monster-link-title.name",
          hint: "ddb-importer.settings.monster-link-title.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "character-link-title": {
          name: "ddb-importer.settings.character-link-title.name",
          hint: "ddb-importer.settings.character-link-title.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: false,
        },
        "link-title-colour-white": {
          name: "ddb-importer.settings.link-title-colour-white.name",
          hint: "ddb-importer.settings.link-title-colour-white.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: false,
        },
        "show-munch-top": {
          name: "ddb-importer.settings.show-munch-top.name",
          hint: "ddb-importer.settings.show-munch-top.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "show-image-to-players": {
          name: "ddb-importer.settings.show-image-to-players.name",
          hint: "ddb-importer.settings.show-image-to-players.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
      },
      PERMISSIONS: {
        "restrict-to-trusted": {
          name: "ddb-importer.settings.restrict-to-trusted.name",
          hint: "ddb-importer.settings.restrict-to-trusted.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: false,
        },
        "allow-all-sync": {
          name: "ddb-importer.settings.allow-all-sync.name",
          hint: "ddb-importer.settings.allow-all-sync.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: false,
        },
      },
      PARSING: {
        "use-full-source": {
          name: "ddb-importer.settings.use-full-source.name",
          hint: "ddb-importer.settings.use-full-source.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "use-damage-hints": {
          name: "ddb-importer.settings.use-damage-hints.name",
          hint: "ddb-importer.settings.use-damage-hints.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "add-damage-restrictions-to-hints": {
          name: "ddb-importer.settings.add-damage-restrictions-to-hints.name",
          hint: "ddb-importer.settings.add-damage-restrictions-to-hints.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "embed-macros": {
          name: "ddb-importer.settings.embed-macros.name",
          hint: "ddb-importer.settings.embed-macros.hint",
          scope: "world",
          config: true,
          type: Boolean,
          default: true,
        },
        "add-description-to-chat": {
          name: "ddb-importer.settings.add-description-to-chat.name",
          hint: "ddb-importer.settings.add-description-to-chat.hint",
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
      },
      // ????
      MISC: {
        "use-webp": {
          name: "ddb-importer.settings.use-webp.name",
          hint: "ddb-importer.settings.use-webp.hint",
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "webp-quality": {
          name: "ddb-importer.settings.webp-quality.name",
          hint: "ddb-importer.settings.webp-quality.hint",
          scope: "world",
          config: false,
          type: Number,
          default: 0.9,
        },
        "settings-call-muncher": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "update-check": {
          scope: "world",
          config: false,
          type: Boolean,
          default: true,
        },
      },
      // character settings
      CHARACTER: {
        IMPORT: {
          "pact-spells-prepared": {
            scope: "world",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-add-character-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-race-damages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-race-speed": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-race-senses": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-race-hp": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-race-spell-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-effect-class-damages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-class-speed": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-class-senses": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-class-hp": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-class-spell-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-effect-feat-proficiencies": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-languages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-damages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-speed": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-senses": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-hp": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-feat-spell-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-effect-feat-ability-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-proficiencies": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-languages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-damages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-speed": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-senses": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-hp": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-effect-background-spell-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-effect-background-ability-bonus": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-scalevalue": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-add-item-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-add-spell-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-generate-ac-feature-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-existing": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-ignore-non-ddb-items": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-override": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-srd": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-name": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-hp": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-hit-die": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-class": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-feat": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-weapon": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-equipment": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-bio": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-languages": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-import-extras": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-inventory": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-currency": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-spell": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-image": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-ddb-spell-icons": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-use-ddb-generic-item-icons": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-use-ddb-item-icons": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-use-inbuilt-icons": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-use-srd-icons": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-full-description": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-use-action-and-feature": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-use-actions-as-features": {
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "character-update-policy-dae-copy": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-dae-effect-copy": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-active-effect-copy": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "character-update-policy-active-effect-character-copy": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
        },
        SYNC: {
          "sync-policy-currency": {
            name: "ddb-importer.settings.sync-policy-currency.name",
            hint: "ddb-importer.settings.sync-policy-currency.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-hitpoints": {
            name: "ddb-importer.settings.sync-policy-hitpoints.name",
            hint: "ddb-importer.settings.sync-policy-hitpoints.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-hitdice": {
            name: "ddb-importer.settings.sync-policy-hitdice.name",
            hint: "ddb-importer.settings.sync-policy-hitdice.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-action-use": {
            name: "ddb-importer.settings.sync-policy-action-use.name",
            hint: "ddb-importer.settings.sync-policy-action-use.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-inspiration": {
            name: "ddb-importer.settings.sync-policy-inspiration.name",
            hint: "ddb-importer.settings.sync-policy-inspiration.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-condition": {
            name: "ddb-importer.settings.sync-policy-condition.name",
            hint: "ddb-importer.settings.sync-policy-condition.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-deathsaves": {
            name: "ddb-importer.settings.sync-policy-deathsaves.name",
            hint: "ddb-importer.settings.sync-policy-deathsaves.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-spells-prepared": {
            name: "ddb-importer.settings.sync-policy-spells-prepared.name",
            hint: "ddb-importer.settings.sync-policy-spells-prepared.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-spells-slots": {
            name: "ddb-importer.settings.sync-policy-spells-slots.name",
            hint: "ddb-importer.settings.sync-policy-spells-slots.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-spells-sync": {
            name: "ddb-importer.settings.sync-policy-spells-sync.name",
            hint: "ddb-importer.settings.sync-policy-spells-sync.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-equipment": {
            name: "ddb-importer.settings.sync-policy-equipment.name",
            hint: "ddb-importer.settings.sync-policy-equipment.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "sync-policy-xp": {
            name: "ddb-importer.settings.sync-policy-xp.name",
            hint: "ddb-importer.settings.sync-policy-xp.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
        },
        DYNAMIC_SYNC: {
          "dynamic-sync-policy-currency": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-hitpoints": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-hitdice": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-action-use": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-inspiration": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-condition": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-deathsaves": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-spells-prepared": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-spells-slots": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-spells-sync": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-equipment": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "dynamic-sync-policy-xp": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
        },
      },
      // muncher settings
      MUNCHER: {
        COMPENDIUM_FOLDERS: {
          "munching-selection-compendium-folders-monster": {
            name: "ddb-importer.settings.munching-selection-compendium-folders-monster.name",
            hint: "ddb-importer.settings.munching-selection-compendium-folders-monster.hint",
            scope: "world",
            config: true,
            type: String,
            choices: {
              TYPE: "Creature type, e.g. Undead",
              CR: "Challenge Rating",
              ALPHA: "Alphabetical",
            },
            default: "TYPE",
          },
          "munching-selection-compendium-folders-spell": {
            name: "ddb-importer.settings.munching-selection-compendium-folders-spell.name",
            hint: "ddb-importer.settings.munching-selection-compendium-folders-spell.hint",
            scope: "world",
            config: true,
            type: String,
            choices: {
              SCHOOL: "School of Magic",
              LEVEL: "Level",
            },
            default: "SCHOOL",
          },
          "munching-selection-compendium-folders-item": {
            name: "ddb-importer.settings.munching-selection-compendium-folders-item.name",
            hint: "ddb-importer.settings.munching-selection-compendium-folders-item.hint",
            scope: "world",
            config: true,
            type: String,
            choices: {
              TYPE: "Item Type",
              RARITY: "Rarity",
            },
            default: "TYPE",
          },
        },
        MUNCH: {
          "munching-policy-update-existing": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-srd": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-compendium-folders": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-srd-icons": {
            name: "ddb-importer.settings.munching-policy-use-srd-icons.name",
            hint: "ddb-importer.settings.munching-policy-use-srd-icons.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-inbuilt-icons": {
            name: "ddb-importer.settings.munching-policy-use-inbuilt-icons.name",
            hint: "ddb-importer.settings.munching-policy-use-inbuilt-icons.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-use-ddb-item-icons": {
            name: "ddb-importer.settings.munching-policy-use-ddb-item-icons.name",
            hint: "ddb-importer.settings.munching-policy-use-ddb-item-icons.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-use-ddb-spell-icons": {
            name: "ddb-importer.settings.munching-policy-use-ddb-spell-icons.name",
            hint: "ddb-importer.settings.munching-policy-use-ddb-spell-icons.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-use-ddb-generic-item-icons": {
            name: "ddb-importer.settings.munching-policy-use-ddb-generic-item-icons.name",
            hint: "ddb-importer.settings.munching-policy-use-ddb-generic-item-icons.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-use-full-token-image": {
            name: "ddb-importer.settings.munching-policy-use-full-token-image.name",
            hint: "ddb-importer.settings.munching-policy-use-full-token-image.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-token-avatar-image": {
            name: "ddb-importer.settings.munching-policy-use-token-avatar-image.name",
            hint: "ddb-importer.settings.munching-policy-use-token-avatar-image.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-remote-images": {
            name: "ddb-importer.settings.munching-policy-remote-images.name",
            hint: "ddb-importer.settings.munching-policy-remote-images.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-add-effects": {
            name: "ddb-importer.settings.munching-policy-add-effects.name",
            hint: "ddb-importer.settings.munching-policy-add-effects.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-add-spell-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-add-monster-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-add-ac-armor-effects": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-download-images": {
            name: "ddb-importer.settings.munching-policy-download-images.name",
            hint: "ddb-importer.settings.munching-policy-download-images.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-dae-copy": {
            name: "ddb-importer.settings.munching-policy-dae-copy.name",
            hint: "ddb-importer.settings.munching-policy-dae-copy.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-dae-effects": {
            name: "ddb-importer.settings.munching-policy-use-dae-effects.name",
            hint: "ddb-importer.settings.munching-policy-use-dae-effects.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-hide-description": {
            name: "ddb-importer.settings.munching-policy-hide-description.name",
            hint: "ddb-importer.settings.munching-policy-hide-description.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-monster-items": {
            name: "ddb-importer.settings.munching-policy-monster-items.name",
            hint: "ddb-importer.settings.munching-policy-monster-items.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-monster-homebrew": {
            name: "ddb-importer.settings.munching-policy-monster-homebrew.name",
            hint: "ddb-importer.settings.munching-policy-monster-homebrew.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-monster-homebrew-only": {
            name: "ddb-importer.settings.munching-policy-monster-homebrew-only.name",
            hint: "ddb-importer.settings.munching-policy-monster-homebrew-only.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-update-images": {
            name: "ddb-importer.settings.munching-policy-update-images.name",
            hint: "ddb-importer.settings.munching-policy-update-images.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-monster-exact-match": {
            name: "ddb-importer.settings.munching-policy-monster-match.name",
            hint: "ddb-importer.settings.munching-policy-monster-match.hint",
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-use-source-filter": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-muncher-sources": {
            scope: "player",
            config: false,
            type: Array,
            default: [],
          },
          "munching-policy-monster-use-item-ac": {
            scope: "player",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-monster-retain-biography": {
            scope: "world",
            config: false,
            type: Boolean,
            default: false,
          },
          "munching-policy-update-world-monster-update-images": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "munching-policy-update-world-monster-retain-biography": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
        },
        ENCOUNTER: {
          "encounter-import-policy-create-scene": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "encounter-import-policy-existing-scene": {
            scope: "world",
            config: false,
            type: Boolean,
            default: false,
          },
          "encounter-import-policy-missing-characters": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "encounter-import-policy-missing-monsters": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "encounter-import-policy-create-journal": {
            scope: "world",
            config: false,
            type: Boolean,
            default: true,
          },
          "encounter-import-policy-roll-monster-initiative": {
            scope: "world",
            config: false,
            type: Boolean,
            default: false,
          },
          "encounter-import-policy-use-ddb-save": {
            scope: "world",
            config: false,
            type: Boolean,
            default: false,
          },
        },
      },
      DYNAMIC_SYNC: {
        "dynamic-sync": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "dynamic-sync-user": {
          scope: "world",
          config: false,
          type: String,
          default: "",
        },
      },
      PROXY: {
        "api-endpoint": {
          scope: "world",
          config: false,
          type: String,
          default: "https://proxy.ddb.mrprimate.co.uk",
        },
        "cors-endpoint": {
          scope: "world",
          config: false,
          type: String,
          default: "https://images.ddb.mrprimate.co.uk/",
        },
        "dynamic-api-endpoint": {
          scope: "world",
          config: false,
          type: String,
          default: "https://dynamic.ddb.mrprimate.co.uk",
        },
        "cors-encode": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "beta-key": {
          scope: "world",
          config: false,
          type: String,
          default: "",
        },
        "patreon-user": {
          scope: "world",
          config: false,
          type: String,
          default: null,
        },
        "cobalt-cookie": {
          name: "ddb-importer.settings.cobalt-cookie.name",
          hint: "ddb-importer.settings.cobalt-cookie.hint",
          scope: "world",
          config: false,
          type: String,
          default: "",
        },
        "cobalt-cookie-local": {
          name: "ddb-importer.settings.cobalt-cookie-local.name",
          hint: "ddb-importer.settings.cobalt-cookie-local.hint",
          scope: "world",
          config: false,
          type: Boolean,
          default: true,
        },
        "campaign-id": {
          name: "ddb-importer.settings.campaign-id.name",
          hint: "ddb-importer.settings.campaign-id.hint",
          scope: "world",
          config: false,
          type: String,
          default: "",
        },
      },
      // dev settings
      DEV: {
        "allow-scene-download": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "allow-third-party-scene-download": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "third-party-scenes-partial": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "allow-note-generation": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
        "debug-json": {
          scope: "player",
          config: false,
          type: Boolean,
          default: false,
        },
        "adventure-muncher-full-config": {
          scope: "world",
          config: false,
          type: Boolean,
          default: false,
        },
      },
    },
  },
  GET_DEFAULT_SETTINGS(early = false) {
    const clone = foundry.utils.deepClone(SETTINGS.DEFAULT_SETTINGS);
    return early
      ? clone.EARLY
      : {
        ...clone.READY.DEV,
        ...clone.READY.SETTINGS,
        ...clone.READY.PROXY,
        ...clone.READY.COMPENDIUMS,
        ...clone.READY.DIRECTORIES,
        ...clone.READY.UI,
        ...clone.READY.PERMISSIONS,
        ...clone.READY.PARSING,
        ...clone.READY.MISC,
        ...clone.READY.CHARACTER.IMPORT,
        ...clone.READY.CHARACTER.SYNC,
        ...clone.READY.DYNAMIC_SYNC,
        ...clone.READY.CHARACTER.DYNAMIC_SYNC,
        ...clone.READY.MUNCHER.COMPENDIUM_FOLDERS,
        ...clone.READY.MUNCHER.MUNCH,
        ...clone.READY.MUNCHER.ENCOUNTER,
      };
  },
};

export default SETTINGS;
