// fallow-ignore-file
// This file is auto-generated by _linkBuilder.js. Do not edit directly.
export { default as FlameDamage } from "./FlameDamage";
export { default as MoveAndAttack } from "./MoveAndAttack";

